| Google Colab | GitHub |
| :---: | :---: |
| <a target="_blank" href="https://colab.research.google.com/github/sadrasabouri/pyrandwalk/blob/master/Document/Examples.ipynb"><img src="https://i.ibb.co/2P3SLwK/colab.png"  style="padding-bottom:5px;" height="50px" weight="50px" /><br>Run in Google Colab</a> | <a target="_blank" href="https://github.com/sadrasabouri/pyrandwalk/blob/master/Document/Examples.ipynb"><img src="https://i.ibb.co/xfJbPmL/github.png"  height="50px" weight="50px" style="padding-bottom:5px;"/><br>View Source on GitHub</a> |

# Pyrandwalk Examples

### Version : 0.09
-----

This example set contains bellow examples from the first reference (Introduction to Stochastic Processes):
<ul>
    <ol>
        <li><a href="#Finite_Markov_Chains">Finite_Markov_Chains</a></li>
        <ul>
            <li><a href="#Exercise1_2">#Exercise1_2</a></li>
            <li><a href="#Exercise1_3">#Exercise1_3</a></li>
            <li><a href="#Exercise1_4">#Exercise1_4</a></li>
        </ul>
    </ol>
</ul>

In [1]:
!pip install pyrandwalk
from pyrandwalk import *
import numpy as np

## 1. Finite_Markov_Chains

### Exercise1_2

Consider a Markov chain with state space \{0, 1\} and transition matrix

$$
P =
\left(\begin{array}{cc} 
1/3 & 2/3\\
3/4 & 1/4
\end{array}\right)
$$

In [2]:
states = [0, 1]
trans = np.array([[1/3, 2/3],
                  [3/4, 1/4]])
rw = RandomWalk(states, trans)

Assuming that the chain starts in state 0 at time n = 0, what is the probability that it is in state 1 at time n = 3?

In [3]:
third_step_trans = rw.trans_power(3)
print(third_step_trans)
print("ANSWER:", third_step_trans[0, 1])

[[0.49537037 0.50462963]
 [0.56770833 0.43229167]]
ANSWER: 0.5046296296296297


### Exercise1_3

Consider a Markov chain with state space \{1, 2, 3\} and transition matrix

$$
P =
\left(\begin{array}{cc} 
0.4 & 0.2 & 0.4\\
0.6 & 0 & 0.4 \\
0.2 & 0.5 & 0.3
\end{array}\right)
$$


In [4]:
states = [1, 2, 3]
trans = np.array([[0.4, 0.2, 0.4],
                  [0.6,  0 , 0.4],
                  [0.2, 0.5, 0.3]])
rw = RandomWalk(states, trans)

what is the probability in the long run that the chain is in state 1?
Solve this problem two different ways:

1) by raising the matrix to a high power:

In [5]:
rw.trans_power(1000)

array([[0.37878788, 0.25757576, 0.36363636],
       [0.37878788, 0.25757576, 0.36363636],
       [0.37878788, 0.25757576, 0.36363636]])

2) by directly computing the invariant probability vector as a left eigenvector:

In [6]:
rw.final_dist()

array([0.37878788, 0.25757576, 0.36363636])

### Exercise1_4

Do the same with

$$
P =
\left(\begin{array}{cc} 
0.2 & 0.4 & 0.4\\
0.1 & 0.5 & 0.4 \\
0.6 & 0.3 & 0.1
\end{array}\right)
$$


In [7]:
states = [1, 2, 3]
trans = np.array([[0.2, 0.4, 0.4],
                  [0.1, 0.5, 0.4],
                  [0.6, 0.3, 0.1]])
rw = RandomWalk(states, trans)

1) by raising the matrix to a high power:

In [8]:
rw.trans_power(1000)

array([[0.28205128, 0.41025641, 0.30769231],
       [0.28205128, 0.41025641, 0.30769231],
       [0.28205128, 0.41025641, 0.30769231]])

2) by directly computing the invariant probability vector as a left eigenvector:

In [9]:
rw.final_dist()

array([0.28205128, 0.41025641, 0.30769231])